version: "3.8"
services:
  app:
    container_name: test-node-api
    image: test-node-img
    restart: always
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    depends_on:
      - mongodb-db
  mongodb-db:
    container_name: test-mongodb
    image: mongo
    restart: always
    ports:
      - "${MGDB_PORT}:${MGDB_PORT}"
    volumes:
      - mongodb_data:/data/db
    command: mongod --quiet --logpath /dev/null 

volumes:
  mongodb_data: